bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('<int:user_id>/', views.index, name = 'index'),
]

pocketguide/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookings/', include('bookings.urls'), name = 'bookings'),
    path('ptgride/', include('ptgride.urls'), name = 'ptgride')
]

ptgride/urls.py
from django.urls import path
from . import views

app_name = 'ptgride'

urlpatterns = [
    path('<int:user_id>/', views.index, name='index'),
    path('<int:user_id>/book', views.book, name = 'book')
]

bookings/models.py
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=25)
    surename = models.CharField(max_length=25)

class Booking(models.Model):
    name = models.CharField(max_length=100)
    type = models.IntegerField()  # {1:flight, 2:accommodation, 3:entertainment}
    time_begin = models.DateTimeField('booking time begin')
    time_end = models.DateTimeField('booking time end')
    location = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

ptgride/models.py
from django.db import models
from bookings.models import User

class Location(models.Model):
    name = models.CharField(max_length=100)
    location = models.IntegerField()

class PtgBooking(models.Model):
    type = models.IntegerField() # {1:ride 2:car}
    time_begin = models.DateTimeField('booking time begin')
    time_end = models.DateTimeField('booking time end')
    pickup_location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='pickup_location')
    dropoff_location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='dropoff_location')
    cost = models.IntegerField()
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)

bookings/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Booking, User
from datetime import datetime

def index(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    booking_list = user.booking_set.all().exclude(time_end__lte=datetime.now())
    context = {
        'booking_list': booking_list,
        'user': user,
    }
    return render(request, 'bookings/index.html', context)

ptgride/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
import faker

from .models import PtgBooking, User, Location

def index(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    booking_list = user.ptgbooking_set.all().exclude(time_end__lte=timezone.now())
    location = Location.objects.all()
    context = {
        'booking_list': booking_list,
        'user': user,
        'location': location
    }
    return render(request, 'ptgride/index.html', context)

def book(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    booking_list = user.ptgbooking_set.all().exclude(time_end__lte=timezone.now())

    try:
        pickup_location = Location.objects.get(name=request.POST['pickup'])
        dropoff_location = Location.objects.get(name=request.POST['dropoff'])
    except (KeyError, Location.DoesNotExist):
        return render(request, 'ptgride/index.html', {
            'booking_list': booking_list,
            'user': user,
            'location': location,
            'error_message': "You didn't select a choice, or choice invalid.",
        })
    
    if (request.POST['choice'] == 'Ride'):
        type = 1
    else:
        type = 2

    print(request.POST['pickup'])

    booking = PtgBooking.objects.create(
        type=type,
        time_begin=timezone.now(),
        time_end=timezone.now() + timezone.timedelta(days=1),
        pickup_location=pickup_location,
        dropoff_location=dropoff_location,
        cost=faker.Faker().random.randint(10000, 25000),
        user = User.objects.get(id=user_id)       
    )

    return HttpResponseRedirect(reverse('ptgride:index', args=(user.id,)))

bookings/templates/bookings/index.html
<h2>User : {{user.first_name}} {{user.surename}}, UID : {{user.id}}</h2>
<h2>Bookings</h2>
{% if booking_list %}
    <ul>
    {% for booking in booking_list %}
        <li>{{ booking.name }}, {{booking.time_begin}} - {{booking.time_end}}, {{booking.location}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bookings are available.</p>
{% endif %}

ptgride/templates/ptgride/index.html
<h2>User : {{user.first_name}} {{user.surename}}, UID : {{user.id}}</h2>
<h2>Ptg Ride</h2>
<h3>Your PtgRide Bookings</h3>

{% if booking_list %}
    <ul>
    {% for booking in booking_list %}
        <li> Booking ID : {{booking.id}} | From {{booking.pickup_location.name}} to {{booking.dropoff_location.name}} | Booking type : {{booking.type}} | Cost : IDR {{booking.cost}},-</li>
    {% endfor %}
    </ul>
{% else %}
    <p> No bookings are available</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'ptgride:book' user.id %}" method="post">
    {% csrf_token %}
    <label for="pickup">Pick-up Location</label><br>
    <input type="text" name="pickup" id="pickup"><br>
    <label for="pickup">Drop-off Location</label><br>
    <input type="text" name="dropoff" id="dropoff"><br>

    <select name="choice">
        <option>Ride</option>
        <option>Car</option>
    </select><br>

    <input type="submit" value="Book">
</form>